dist: xenial
language: python
python:
  - "3.7"

virtualenv:
  system_site_packages: true

env:
  - TOXENV=django111_py37
  - TOXENV=django22_py37

  - TOXENV=coverage

install:
  - pip install tox
  - sudo apt install python-gdal

script: tox
